# @name login
POST http://127.0.0.1:3000/api/user/login HTTP/1.1
content-type: application/json

{
    "userName": "admin",
    "userPassword": "123456"
}

###

POST http://127.0.0.1:3000/api/admin-sqlite/backup-database HTTP/1.1
content-type: application/json
Authorization: Bearer {{login.response.body.data.token}}

{}