services:
  app:
    image: lsby-punch-in-prod
    build:
      context: ../../
      dockerfile: ./deploy/production/dockerfile
    ports:
      - 9002:80
    env_file:
      - ../../.env/.env.production
    restart: always
    volumes:
      - ../../db:/opt/app/db
