# ====================
# 构建阶段
# ====================
FROM node:22 AS builder

ENV TZ=Asia/Shanghai
WORKDIR /opt/app

COPY . .

RUN corepack enable && \
    pnpm install
RUN export PARCEL_WORKER_BACKEND=process && \
    npm run _build:all

# 初始化默认数据库
RUN echo "\n" | npm run db:push:prod

# ====================
# 安装阶段
# ====================
FROM node:22 AS installer

ENV TZ=Asia/Shanghai
WORKDIR /opt/app

COPY --from=builder /opt/app/package.json /opt/app/
COPY --from=builder /opt/app/pnpm-lock.yaml /opt/app/

RUN corepack enable && \
    pnpm install --prod --ignore-scripts

# ====================
# 运行阶段
# ====================
FROM node:22-alpine

ENV TZ=Asia/Shanghai
WORKDIR /opt/app

COPY --from=builder /opt/app/db/prod.db /opt/app/db-default-prod.db
COPY --from=installer /opt/app/node_modules /opt/app/node_modules
COPY --from=builder /opt/app/package.json /opt/app/
COPY --from=builder /opt/app/dist /opt/app/dist
COPY --from=builder /opt/app/public /opt/app/public
COPY --from=builder /opt/app/.env/.env.production /opt/app/.env/.env.production

EXPOSE 80

CMD ["sh", "-c", "mkdir -p /opt/app/db; if [ ! -f /opt/app/db/prod.db ]; then echo 'Initializing database from default'; cp /opt/app/db-default-prod.db /opt/app/db/prod.db; else echo 'Database already exists'; fi && npm run run:service:prod"]
